version: '3.1'

services:
  app:
    build: .
    command: ["./entrypoint.sh", "uvicorn", "fairytale_ai_server.asgi:application", "--host", "0.0.0.0", "--port", "8000", "--lifespan", "off"]
    volumes:
      - ./fairytale_ai_server:/fairytale_ai_server
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:17.0-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}

volumes:
  postgres_data:
